### ISSUE TITLE
Allow reverting to the old style

### ISSUE THREAD

**Issue by skaldebane** [CharlieQLe/gnome-extension-dotspaces#3]
Hi! First, thanks for this wonderful extension.

It's recently been updated on my machine, just for it to lose the extra margins (I liked it!), as well as the + icon for the extra empty workspace when using dynamic workspaces.

It would be great if you'd allow reverting to that style, or more reasonably, allow users to choose the exact margins and the option to get back the + icon.

**Edit:** I guess the + icon disappearing (now it's just an empty circle) on dynamic workspaces counts as a bug? The README still cites that it should show + in that case.

**Comment by CharlieQLe** [comment]
There's now a padding adjustment setting and the + icon has been fixed in the main branch. I'll publish this update to EGO at some point in the future.
